### PR TITLE
header section added

### PR DESCRIPTION
**Pull request by tawhidwebdev**
creating header with text

### CODE REVIEW

**Comment by tawhidwebdev** [comment]
> /* css start here */ why cut this line

i cut this becuse i did not like the ui

**Review by taufik69 — CHANGES_REQUESTED** [review]
change the backgroud color

**Comment by tawhidwebdev** [comment]
> change the backgroud color

korbo na tk den

**Comment by tawhidwebdev** [comment]
> change the backgroud color

done

**Pull request merged**
